### ISSUE TITLE
Support for VerbalExpressions?

### ISSUE THREAD

**Issue by aadrian** [geongeorge/i-hate-regex#11]
Hi,

The diagram rendering of a regexp is very nice and helpful.

Any chance adding support for Verbal Expressions? https://github.com/VerbalExpressions -> they seem to map in "words" very nicely the diagram blocks.

So the idea would be for a regexp like `/^(http)(s)?(\:\/\/)(www\.)?([^\ ]*)$/`
to also generate besides the diagram the VerbalExpression text alternative:
```JS
const tester = VerEx()
    .startOfLine()
    .then('http')
    .maybe('s')
    .then('://')
    .maybe('www.')
    .anythingBut(' ')
    .endOfLine();
```
for the desired programming language.

See https://github.com/VerbalExpressions/JSVerbalExpressions#testing-if-we-have-a-valid-url

Thank you.

**Comment by geongeorge** [comment]
This is something we find unnecessary, Closing it for now
