### ISSUE TITLE
Mention \p{Letter} as alternative to [a-zA-Z]

### ISSUE THREAD

**Issue by JacksonBailey** [geongeorge/i-hate-regex#26]
See [here](https://www.regular-expressions.info/unicode.html) for more info. Basically using `\p{Letter}` (or the shortened `\p{L}`) matches any unicode character that is a letter. This way you match things like `ñ`.

**Comment by geongeorge** [comment]
> \p{L} or \p{Letter}: any kind of letter from any language.

It is not the same as `[a-zA-Z]` which is only English alphabets from a-z in both casing

**Comment by geongeorge** [comment]
I'm closing this issue. Feel free to open a new issue if you feel it's still wrong

**Comment by JacksonBailey** [comment]
> which is only English alphabets

Yeah, that's the whole problem! I even said it matches things like "ñ" in the original issue.

`[a-zA-Z]+` won't match things like "José". For example, say you want to make regex to validate users' display names and want to allow people to use letters from their native languages. You could use something like `\p{L}+` to allow things like "José".

**Comment by geongeorge** [comment]
I do not match "é" or "ñ".
it is not supposed to because a username is usually used in the url like:
`https://twitter.com/geongeorgek`

where `geongeorgek` is my username

A url can only contain ASCII characters

![image](https://user-images.githubusercontent.com/29296982/73899707-60498c00-48b3-11ea-8140-1479e3595241.png)

**Comment by JacksonBailey** [comment]
That's why I suggested "display name" instead of user name. But it's a bad
example, I just think there are a lot of cases people want to match "any
ketter" but they default to `[a-zA-Z]` because they don't know of any other
option, and I think a quick tool like your site would be a great place for
an example like this so more people know about it.
