### ISSUE TITLE
Cant catch a single word line.

### ISSUE THREAD

**Issue by aprekates** [geongeorge/i-hate-regex#31]
I tried  ^foo$ 
but it wont work.
foo$ works
and    ^foo

**Comment by geongeorge** [comment]
Just tried and it works.

<a href="https://user-images.githubusercontent.com/29296982/73925132-927ade00-48f3-11ea-8b98-4eb83ab52191.png" width=300>


did you try waiting a second for the highlighting to happen?

**Comment by geongeorge** [comment]
I'm closing this issue. You are free to open it again 😄
