### ISSUE TITLE
Is there a bug in the online CheatSheet?

### ISSUE THREAD

**Issue by Gitoo22** [geongeorge/i-hate-regex#52]
Hello I.H.R. DreamTeam,

First congrats for this useful tool, and thanks for your work.

This cheat sheet ( https://ihateregex.io/cheatsheet ) says : 
/h.llo/	the '.' matches any one character other than a new line character... matches 'hello', 'hallo' but not 'h llo'

I am afraid I disagree : The last target "h" SPACE "llo" is matched by "/h.llo/", don't you think?
You may have wanted to write "hllo", isn't it?

KUTGW & best regards.

**Comment by geongeorge** [comment]
You are right 👍 
Thanks for pointing this out

**Comment by geongeorge** [comment]
It isn't supposed to be `hello` but should have been
```
h
llo
```
Since `.` matches all characters except for a `newline`

did not properly display the new line character because it did not support html.
I have added html support hence fixing the issue here: 2c36269a2a9b21a5de9fc71e0da99eebb43931fd
