### ISSUE TITLE
'username' regex doesn't match description

### ISSUE THREAD

**Issue by linus345** [geongeorge/i-hate-regex#64]
The regex for matching usernames doesn't match the given description. 

**Given description:**

> Alphanumeric string that may include _ and - having a length of 3 to 16 characters.
> A username must not contain 2 underscores or 2 hyphens in a row. Also, it cannot have an 
> underscore, hyphen or a space at the start.

**But it still matches strings like:**

- `-ab`
- `a--b`
- `a__`

**Fix:**
Either change the description or the regex.

Here's a regex that follows the description **except** the minimum and maximum amount of characters allowed. `/^[a-zA-Z0-9]+([_-]?[a-zA-Z0-9])*$/`

**Comment by geongeorge** [comment]
Thanks for reporting. I guess it's better to fix the description :)
Any thoughts?

**Comment by geongeorge** [comment]
Fixed it here: fed1d4345c2e4835c347e7c7160844acfc029995

Closing this for now. Please reply if you have any suggestions :)
