### ISSUE TITLE
issue with regex for ip address(ipv4)

### ISSUE THREAD

**Issue by Donnyp751** [geongeorge/i-hate-regex#82]
I came across a small issue with the regex matching for ipv4, it's supposed to check that the ip address is in the range of 0.0.0.0 to 255.255.255.255 but this can fail when you get a number where just the first octet is larger then 255.
For example the ip address 341.25.015.22 passes because the starting 3 is ignored, then it appears valid. 
Currently the regex for ipv4 is (25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}
But I believe it should be         (**\b**25[0-5]|**\b**2[0-4][0-9]|**\b**[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3}
to include cases where the initial number may be out of range, but in range if you ignore the first character. The match should begin at the start of the word. Test cases that would be incorrect before, but are resolved by the suggestion below.
341.25.015.22
4248.254.1.1
972.52.4.12
1255.34.22.58

**Comment by geongeorge** [comment]
FIxed here https://github.com/geongeorge/i-hate-regex/pull/83

**Comment by Donnyp751** [comment]
It looks like the website views the \b as a square box, does that need to be escaped or something to display right?
(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)(\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)){3} 
is what comes up on i-hate-regex for ipv4

**Comment by geongeorge** [comment]
I have merged a fix. Can you take a look https://github.com/geongeorge/i-hate-regex/pull/84
