### ISSUE TITLE
Simple email regex - matches invalid emails

### ISSUE THREAD

**Issue by Dr4g0nBlade** [geongeorge/i-hate-regex#85]
https://ihateregex.io/expr/email/
<img width="677" alt="Screenshot 2021-09-20 at 10 10 28" src="https://user-images.githubusercontent.com/10995205/133967865-b0331e80-5a19-43bc-af9a-eab9dbb5431f.png">

The subdomain email is ok.

**Comment by Donnyp751** [comment]
You're using the "email simple" expression. It's not as in-depth as the advanced one. You should try out the "email complicated" if you want those cases covered.
https://ihateregex.io/expr/email-2/
