### ISSUE TITLE
embed.ihateregex.io refused to connect.

### ISSUE THREAD

**Issue by sogeisetsu** [geongeorge/i-hate-regex#91]
i can not find embed picture by using chrome.it showed embed.ihateregex.io refused to connect.

![](https://suyuesheng-biaozhun-blog-tupian.oss-cn-qingdao.aliyuncs.com/blogimg/20220411152351.png)

Does anyone have the same problem as me？

**Comment by sogeisetsu** [comment]
I tried to visit embed.ihateregex.io

it show me a 522 error

![](https://suyuesheng-biaozhun-blog-tupian.oss-cn-qingdao.aliyuncs.com/blogimg/20220411153558.png)

The website embed.ihateregex.io displays the following information

Contact your hosting provider letting them know your web server is not completing requests. An Error 522 means that the request was able to connect to your web server, but that the request didn't finish. The most likely cause is that something on your server is hogging resources. [Additional troubleshooting information here.](https://support.cloudflare.com/hc/en-us/articles/200171906-Error-522)

**Comment by geongeorge** [comment]
This should be fixed now. :) Thanks

**Comment by sogeisetsu** [comment]
> This should be fixed now. :) Thanks

@geongeorge Thanks
